[theme]

# Primary accent for interactive elements
primaryColor = '#EA581D'

# Background color for the main content area
backgroundColor = '#B7FF80'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#FEFBD4'

# Color used for almost all text
textColor = '#FF0303'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"